### ISSUE TITLE
SSL key not valid.

### ISSUE THREAD

**Issue by spludge** [TGS-App/tgs-app.github.io#3]
Only the github domain is registered, so accessing from app.tgs.school.nz is not secured.

**Comment by k-yle** [comment]
Hi, 
yes, HTTPS does not work at the moment, because the TGS IT department cannot apply security certificates at the moment, 
hence why some windows devices cannot connect to the wi-fi either.
       
<br />
         
Although this is an upstream issue which we can't fix right now, I'm going to leave this issue open until we get HTTPS working properly.

**Comment by spludge** [comment]
Seems to be all good now, hope you don't mind if I close it.
