### ISSUE TITLE
README dead links

### ISSUE THREAD

**Issue by spludge** [TGS-App/tgs-app.github.io#4]
Every github.com/ky-le link in the README is dead. I dunno where those repos are, or even if they exist yet, but there is nothing to indicate this.

**Comment by k-yle** [comment]
Hi, these repositories are private. 
If you are a student at TGS and would like to contribute, please provide proof that you go to TGS
(you could email us at tgs0036stapp@tgs.school.nz from your school-email-account referencing this conversation). 

Closing because the issue is invalid.

**Comment by k-yle** [comment]
There are a lot of bugs in KAMARs APIs, some of which could compromise the security of the KAMAR database. A few of these vulnerabilities are used in the backend (albeit for a legitimate reason!), e.g. to show proper attendance codes and explainations instead of just Present or Absent.

If this code is open-sourced, a malicious user could exploit one of these security bugs (e.g. to spoof an admin for attendance and get proper codes) and use the same logic in an attack on the get-students-personal-details endpoint, (by spoofing an admin), and fetching extra details such as students' home address(es).

To avoid being responsible for an attack on KAMAR portals across NZ which could leak such data, I have not-, and will not open source the code until these vulnerabilities are patched.
AFAIK, none of these vulnerabilities are known and documented anywhere online, so I don't want to be the one who exposes a bug which could allow a malicious user to steal confidential information.


Sorry for the inconvenience.



Sent from Outlook for Android

________________________________

**Comment by leifmetcalf** [comment]
Are they all reported to upstream?
